function(add_gmac_sources )
    get_property(gmac_SRC GLOBAL PROPERTY gmac_SRC)
    foreach(__file ${ARGV})
        set(__source __source-NOTFOUND)
        find_file(__source ${__file} ${CMAKE_CURRENT_SOURCE_DIR} NO_DEFAULT_PATH)
        if(EXISTS ${__source})
            set(gmac_SRC ${gmac_SRC} ${__source})
        else()
            set(__binary __binary-NOTFOUND)
            find_file(__binary ${__file} ${CMAKE_CURRENT_BINARY_DIR} NO_DEFAULT_PATH)
            if(EXISTS ${__binary})
                set(gmac_SRC ${gmac_SRC} ${__binary})
            endif()
        endif()
    endforeach()
    set_property(GLOBAL PROPERTY gmac_SRC ${gmac_SRC})
endfunction(add_gmac_sources)

